http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https_redirect
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
    traefik:
      rule: "Host(`{{DOMAIN}}`)"
      entryPoints:
        - https
      tls:
        certResolver: dns_cloudflare
      service: api@internal
    qbit:
      rule: "Host(`{{DOMAIN}}`) && PathPrefix(`/qbit`)"
      entryPoints:
        - https
      tls:
        certResolver: dns_cloudflare
      service: qbit@docker
      middlewares: 
        - "prefix_chain"

  services:
      noop:
        loadBalancer:
          servers:
            - url: "http://127.0.0.1"

  middlewares:
    prefix_chain:
      chain:
        middlewares:
          - append_slash_redirect
          - strip_prefix
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true
    append_slash_redirect:
      redirectRegex:
        regex: "^(https?://[^/]+/[a-z0-9_]+)$"
        replacement: "${1}/"
        permanent: true
    strip_prefix:
      stripPrefixRegex:
        regex:
          - "/[a-z0-9_]+"

    