http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https_redirect
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
      
    traefik:
      rule: "Host(`traefik.{{DOMAIN}}`)"
      entryPoints:
        - https
      tls:
        certResolver: dns_cloudflare
        domains:
          - main: "{{DOMAIN}}"
            sans:
              - "*.{{DOMAIN}}"
      service: api@internal

    qbit:
      rule: "Host(`qbit.{{DOMAIN}}`)"
      entryPoints:
        - https
      service: qbit@docker
      tls:
        certResolver: dns_cloudflare

    plex:
      rule: "Host(`plex.{{DOMAIN}}`)"
      entryPoints:
        - https
      service: plex@docker
      tls:
        certResolver: dns_cloudflare
      
    heimdall:
      rule: "Host(`{{DOMAIN}}`)"
      entryPoints:
        - https
      service: heimdall@docker
      tls:
        certResolver: dns_cloudflare

  services:
      noop:
        loadBalancer:
          servers:
            - url: "http://127.0.0.1"

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true

    