http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https_redirect
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
    traefik:
      rule: "Host(traefik.`{{DOMAIN}}`)"
      entryPoints:
        - https
      tls:
        certResolver: dns_cloudflare
      service: api@internal
    qbit:
      rule: "Host(`qbit.{{DOMAIN}}`)"
      entryPoints:
        - https
      tls:
        certResolver: dns_cloudflare
      service: qbit@docker

    plex:
      rule: "Host(plex.`{{DOMAIN}}`)"
      entryPoints:
        - https
      tls:
        certResolver: dns_cloudflare
      service: plex@docker

  services:
      noop:
        loadBalancer:
          servers:
            - url: "http://127.0.0.1"

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true

    