http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https_redirect
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
    traefik:
      rule: "Host(`${DOMAIN}`)"
      entryPoints:
        - https
      tls:
        certResolver: dns_cloudflare
      service: api@internal
    qbit:
      rule: "Host(`${DOMAIN}`) && PathPrefix(`/qbit`)"
      entryPoints:
        - https
      tls:
        certResolver: dns_cloudflare
      service: qbit@docker
      middlewares: 
        - "prefix_stripper"
        - "qbit_headers"

  services:
      noop:
        loadBalancer:
          servers:
            - url: "http://127.0.0.1"

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true
    prefix_stripper:
      stripPrefix:
        prefixes:
          - '/qbit'
    qbit_headers:
      headers:
        customRequestHeaders:
          X-Frame-Options: "SAMEORIGIN"
          Referer: ""
          Origin: ""
      