http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https_redirect
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
    traefik:
      rule: "Host(`${DOMAIN}`)"
      entryPoints:
        - https
      tls:
        certResolver: dns-cloudflare
      service: api@internal
    qbit:
      rule: "Host(`${DOMAIN}`) && PathPrefix(`/qbit`)"
      entryPoints:
        - https
      tls:
        certResolver: dns-cloudflare
      service: qbit@docker
  
  middlewares:
    prefix-stripper:
      stripPrefix:
        prefixes:
          - '/qbit'
        forceSlash: false


  services:
      noop:
        loadBalancer:
          servers:
            - url: "http://127.0.0.1"

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true