global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: INFO

accessLog:
  filePath: "/var/log/docker/traefik.log"
  bufferingSize: 100
  filters:
    statusCodes: 
      - "400-499"

entryPoints:
  http:
    address: :80
  https:
    address: :443

certificatesResolvers:
  dns-cloudflare:
    acme:
      email: ${EMAIL}
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare

providers:
  file:
    directory: "/etc/traefik/dynamic"
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_proxy

api:
  dashboard: true
ping:
  entryPoint: http
