version: "3.7"

########################### 
#   NETWORKS
###########################
networks:
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
  default:
    driver: bridge

########################### 
#   SERVICES
###########################
services:

  ########################### 
  #   FRONT ENDS
  ###########################

  # Traefik - Reverse Proxy
  traefik:
    image: traefik:v2.1.3
    container_name: traefik
    restart: unless-stopped
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../certificates/acme/acme.json:/acme.json
      - ../traefik/traefik.log:/var/log/docker/traefik.log
      - ../traefik/traefik.yml:/etc/traefik/traefik.yml
      - ../traefik/dynamic:/etc/traefik/dynamic
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
  
  # qBittorrent - Torrent downloader
  qbittorrent:
    image: wootencl/pia-qbit
    container_name: qbit
    restart: unless-stopped
    networks:
      - traefik_proxy
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads
    environment:
      REGION: US East
      PROTOCOL: tcp
      USER: ${PIA_USER}
      PASSWORD: ${PIA_PASSWORD}
      DNS_SERVERS: 8.8.8.8, 8.8.4.4
      WEBUI_PORT: 9001
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.qbit.loadbalancer.server.port=9001"

  # Plex - Media Server
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    environment:
      - VERSION=docker
    volumes:
      - /media/home-server-storage/plex:/config
      - /media/home-server-storage/movies:/movies
      - /media/home-server-storage/tv-shows:/tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=9001"
