version: "3.7"

########################### 
#   NETWORKS
###########################
networks:
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
  default:
    driver: bridge

########################### 
#   SERVICES
###########################
services:

  ########################### 
  #   FRONT ENDS
  ###########################

  # Traefik - Reverse Proxy
  traefik:
    container_name: traefik
    image: traefik:v2.0
    restart: always
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme/acme.json:/acme.json
      - ./traefik/traefik.log:/var/log/docker/traefik.log
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.http.routers.traefik.rule=Host(`pi.carterwooten.com`)"
  
  test-app:
    image: containous/whoami
    command:
      - --port=8082
    labels:
      - "traefik.http.routers.test-app.rule=Host(`pi.carterwooten.com`) && Path(`/test`)"