version: "3.7"

########################### 
#   NETWORKS
###########################
networks:
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
  default:
    driver: bridge

########################### 
#   SERVICES
###########################
services:

  ########################### 
  #   FRONT ENDS
  ###########################

  # Traefik - Reverse Proxy
  traefik:
    container_name: traefik
    image: traefik:v2.0
    restart: always
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme/acme.json:/acme.json
      - ./traefik/traefik.log:/var/log/docker/traefik.log
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
  
  # qBittorrent - Torrent downloader
  qbittorrent:
    image: wootencl/pia-qbit
    container_name: qbit
    restart: always
    networks:
      - default
      - traefik_proxy
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads
    environment:
      REGION: US East
      PROTOCOL: tcp
      USER: ${PIA_USER}
      PASSWORD: ${PIA_PASSWORD}
      DNS_SERVERS: 8.8.8.8, 8.8.4.4
      WEBUI_PORT: 8080
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"