http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https_redirect
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
    traefik:
      entryPoints:
        - https
      tls:
        certResolver: dns-cloudflare
      service: traefik
    test-app:
      entryPoints:
        - https
      tls:
        certResolver: dns-cloudflare
      service: test-app

  services:
    noop:
      loadBalancer:
        servers:
          - url: 'http://127.0.0.1'
    traefik: 
      loadBalancer:
        servers:
          - url: 'http://127.0.0.1:8080'
    test-app:
      loadBalancer:
        servers:
          - url: 'http://127.0.0.1:8082'

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true