http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https_redirect
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
    traefik:
      tls:
        certResolver: dns-cloudflare
        domains:
          main: carterwooten.com
          sans: "*.carterwooten.com"

  services:
    noop:
      loadBalancer:
        servers:
          - url: 'http://127.0.0.1'

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true