http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https_redirect
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
    traefik:
      rule: "Host(`pi.carterwooten.com`)"
      entryPoints:
        - https
      tls:
        certResolver: dns-cloudflare
      service: traefik@docker
    test-app:
      entryPoints:
        - https
      tls:
        certResolver: dns-cloudflare
      service: test-app@docker

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true