http:
  routers:
    http_catchall:
      entryPoints:
        - http
      middlewares:
        - https_redirect
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
    traefik:
      rule: "Host(`pi.carterwooten.com`)"
      entryPoints:
        - https
      tls:
        certResolver: dns-cloudflare
      service: api@internal
    test-app:
      rule: "Host(`pi.carterwooten.com`) && Path(`/test`)"
      entryPoints:
        - https
      tls:
        certResolver: dns-cloudflare
      service: test-app@docker
  
  services:
      noop:
        loadBalancer:
          servers:
            - url: "http://127.0.0.1"

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true